// <auto-generated />
using System;
using Kedu.Payments.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kedu.Payments.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226021814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kedu.Payments.Api.Domain.Entities.CentroDeCusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CentrosDeCusto");
                });

            modelBuilder.Entity("Kedu.Payments.Api.Domain.Entities.Cobranca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MetodoPagamento")
                        .HasColumnType("integer");

                    b.Property<int>("PlanoPagamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PlanoPagamentoId");

                    b.ToTable("Cobrancas");
                });

            modelBuilder.Entity("Kedu.Payments.Api.Domain.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CobrancaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CobrancaId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("Kedu.Payments.Api.Domain.Entities.PlanoPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroDeCustoId")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CentroDeCustoId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("Kedu.Payments.Api.Domain.Entities.ResponsavelFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("Kedu.Payments.Api.Domain.Entities.Cobranca", b =>
                {
                    b.HasOne("Kedu.Payments.Api.Domain.Entities.PlanoPagamento", "PlanoPagamento")
                        .WithMany("Cobrancas")
                        .HasForeignKey("PlanoPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoPagamento");
                });

            modelBuilder.Entity("Kedu.Payments.Api.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("Kedu.Payments.Api.Domain.Entities.Cobranca", "Cobranca")
                        .WithMany("Pagamentos")
                        .HasForeignKey("CobrancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobranca");
                });

            modelBuilder.Entity("Kedu.Payments.Api.Domain.Entities.PlanoPagamento", b =>
                {
                    b.HasOne("Kedu.Payments.Api.Domain.Entities.CentroDeCusto", "CentroDeCusto")
                        .WithMany()
                        .HasForeignKey("CentroDeCustoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kedu.Payments.Api.Domain.Entities.ResponsavelFinanceiro", "Responsavel")
                        .WithMany("PlanosDePagamento")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroDeCusto");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Kedu.Payments.Api.Domain.Entities.Cobranca", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Kedu.Payments.Api.Domain.Entities.PlanoPagamento", b =>
                {
                    b.Navigation("Cobrancas");
                });

            modelBuilder.Entity("Kedu.Payments.Api.Domain.Entities.ResponsavelFinanceiro", b =>
                {
                    b.Navigation("PlanosDePagamento");
                });
#pragma warning restore 612, 618
        }
    }
}
